from enum import Enum


class BlockEntityType(Enum):
    BANNER = 'minecraft:banner'
    BARREL = 'minecraft:barrel'
    BEACON = 'minecraft:beacon'
    BED = 'minecraft:bed'
    BEEHIVE = 'minecraft:beehive'
    BELL = 'minecraft:bell'
    BLAST_FURNACE = 'minecraft:blast_furnace'
    BREWING_STAND = 'minecraft:brewing_stand'
    CAMPFIRE = 'minecraft:campfire'
    CHEST = 'minecraft:chest'
    COMMAND_BLOCK = 'minecraft:command_block'
    COMPARATOR = 'minecraft:comparator'
    CONDUIT = 'minecraft:conduit'
    DAYLIGHT_DETECTOR = 'minecraft:daylight_detector'
    DISPENSER = 'minecraft:dispenser'
    DROPPER = 'minecraft:dropper'
    ENCHANTING_TABLE = 'minecraft:enchanting_table'
    END_GATEWAY = 'minecraft:end_gateway'
    END_PORTAL = 'minecraft:end_portal'
    ENDER_CHEST = 'minecraft:ender_chest'
    FURNACE = 'minecraft:furnace'
    HOPPER = 'minecraft:hopper'
    JIGSAW = 'minecraft:jigsaw'
    JUKEBOX = 'minecraft:jukebox'
    LECTERN = 'minecraft:lectern'
    MOB_SPAWNER = 'minecraft:mob_spawner'
    PISTON = 'minecraft:piston'
    SCULK_SENSOR = 'minecraft:sculk_sensor'
    SHULKER_BOX = 'minecraft:shulker_box'
    SIGN = 'minecraft:sign'
    SKULL = 'minecraft:skull'
    SMOKER = 'minecraft:smoker'
    STRUCTURE_BLOCK = 'minecraft:structure_block'
    TRAPPED_CHEST = 'minecraft:trapped_chest'
