from enum import Enum


class PaintingMotive(Enum):
    ALBAN = 'minecraft:alban'
    AZTEC = 'minecraft:aztec'
    AZTEC2 = 'minecraft:aztec2'
    BOMB = 'minecraft:bomb'
    BURNING_SKULL = 'minecraft:burning_skull'
    BUST = 'minecraft:bust'
    COURBET = 'minecraft:courbet'
    CREEBET = 'minecraft:creebet'
    DONKEY_KONG = 'minecraft:donkey_kong'
    FIGHTERS = 'minecraft:fighters'
    GRAHAM = 'minecraft:graham'
    KEBAB = 'minecraft:kebab'
    MATCH = 'minecraft:match'
    PIGSCENE = 'minecraft:pigscene'
    PLANT = 'minecraft:plant'
    POINTER = 'minecraft:pointer'
    POOL = 'minecraft:pool'
    SEA = 'minecraft:sea'
    SKELETON = 'minecraft:skeleton'
    SKULL_AND_ROSES = 'minecraft:skull_and_roses'
    STAGE = 'minecraft:stage'
    SUNSET = 'minecraft:sunset'
    VOID = 'minecraft:void'
    WANDERER = 'minecraft:wanderer'
    WASTELAND = 'minecraft:wasteland'
    WITHER = 'minecraft:wither'
