from enum import Enum


class Potion(Enum):
    AWKWARD = 'minecraft:awkward'
    EMPTY = 'minecraft:empty'
    FIRE_RESISTANCE = 'minecraft:fire_resistance'
    HARMING = 'minecraft:harming'
    HEALING = 'minecraft:healing'
    INVISIBILITY = 'minecraft:invisibility'
    LEAPING = 'minecraft:leaping'
    LONG_FIRE_RESISTANCE = 'minecraft:long_fire_resistance'
    LONG_INVISIBILITY = 'minecraft:long_invisibility'
    LONG_LEAPING = 'minecraft:long_leaping'
    LONG_NIGHT_VISION = 'minecraft:long_night_vision'
    LONG_POISON = 'minecraft:long_poison'
    LONG_REGENERATION = 'minecraft:long_regeneration'
    LONG_SLOW_FALLING = 'minecraft:long_slow_falling'
    LONG_SLOWNESS = 'minecraft:long_slowness'
    LONG_STRENGTH = 'minecraft:long_strength'
    LONG_SWIFTNESS = 'minecraft:long_swiftness'
    LONG_TURTLE_MASTER = 'minecraft:long_turtle_master'
    LONG_WATER_BREATHING = 'minecraft:long_water_breathing'
    LONG_WEAKNESS = 'minecraft:long_weakness'
    LUCK = 'minecraft:luck'
    MUNDANE = 'minecraft:mundane'
    NIGHT_VISION = 'minecraft:night_vision'
    POISON = 'minecraft:poison'
    REGENERATION = 'minecraft:regeneration'
    SLOW_FALLING = 'minecraft:slow_falling'
    SLOWNESS = 'minecraft:slowness'
    STRENGTH = 'minecraft:strength'
    STRONG_HARMING = 'minecraft:strong_harming'
    STRONG_HEALING = 'minecraft:strong_healing'
    STRONG_LEAPING = 'minecraft:strong_leaping'
    STRONG_POISON = 'minecraft:strong_poison'
    STRONG_REGENERATION = 'minecraft:strong_regeneration'
    STRONG_SLOWNESS = 'minecraft:strong_slowness'
    STRONG_STRENGTH = 'minecraft:strong_strength'
    STRONG_SWIFTNESS = 'minecraft:strong_swiftness'
    STRONG_TURTLE_MASTER = 'minecraft:strong_turtle_master'
    SWIFTNESS = 'minecraft:swiftness'
    THICK = 'minecraft:thick'
    TURTLE_MASTER = 'minecraft:turtle_master'
    WATER = 'minecraft:water'
    WATER_BREATHING = 'minecraft:water_breathing'
    WEAKNESS = 'minecraft:weakness'
