from enum import Enum


class StatusEvent(Enum):
    ABSORPTION = 'minecraft:absorption'
    BAD_OMEN = 'minecraft:bad_omen'
    BLINDNESS = 'minecraft:blindness'
    CONDUIT_POWER = 'minecraft:conduit_power'
    DOLPHINS_GRACE = 'minecraft:dolphins_grace'
    FIRE_RESISTANCE = 'minecraft:fire_resistance'
    GLOWING = 'minecraft:glowing'
    HASTE = 'minecraft:haste'
    HEALTH_BOOST = 'minecraft:health_boost'
    HERO_OF_THE_VILLAGE = 'minecraft:hero_of_the_village'
    HUNGER = 'minecraft:hunger'
    INSTANT_DAMAGE = 'minecraft:instant_damage'
    INSTANT_HEALTH = 'minecraft:instant_health'
    INVISIBILITY = 'minecraft:invisibility'
    JUMP_BOOST = 'minecraft:jump_boost'
    LEVITATION = 'minecraft:levitation'
    LUCK = 'minecraft:luck'
    MINING_FATIGUE = 'minecraft:mining_fatigue'
    NAUSEA = 'minecraft:nausea'
    NIGHT_VISION = 'minecraft:night_vision'
    POISON = 'minecraft:poison'
    REGENERATION = 'minecraft:regeneration'
    RESISTANCE = 'minecraft:resistance'
    SATURATION = 'minecraft:saturation'
    SLOW_FALLING = 'minecraft:slow_falling'
    SLOWNESS = 'minecraft:slowness'
    SPEED = 'minecraft:speed'
    STRENGTH = 'minecraft:strength'
    UNLUCK = 'minecraft:unluck'
    WATER_BREATHING = 'minecraft:water_breathing'
    WEAKNESS = 'minecraft:weakness'
    WITHER = 'minecraft:wither'
